

export const vocabulario = [
    // Frutas
    { english: "Apple", spanish: "Manzana" },
    { english: "Banana", spanish: "Plátano" },
    { english: "Orange", spanish: "Naranja" },
    { english: "Strawberry", spanish: "Fresa" },
    { english: "Grapes", spanish: "Uvas" },
    { english: "Watermelon", spanish: "Sandía" },
    { english: "Pineapple", spanish: "Piña" },
    { english: "Mango", spanish: "Mango" },
    { english: "Pear", spanish: "Pera" },
    { english: "Lemon", spanish: "Limón" },
    { english: "Peach", spanish: "Durazno" },
    { english: "Kiwi", spanish: "Kiwi" },
    { english: "Cherry", spanish: "Cereza" },
    { english: "Avocado", spanish: "Aguacate" },
  
    // Colores
    { english: "Red", spanish: "Rojo" },
    { english: "Blue", spanish: "Azul" },
    { english: "Green", spanish: "Verde" },
    { english: "Yellow", spanish: "Amarillo" },
    { english: "Black", spanish: "Negro" },
    { english: "White", spanish: "Blanco" },
    { english: "Pink", spanish: "Rosa" },
    { english: "Purple", spanish: "Púrpura" },
    { english: "Orange", spanish: "Naranja" },
    { english: "Brown", spanish: "Marrón" },
    { english: "Gray", spanish: "Gris" },
    { english: "Beige", spanish: "Beige" },
    { english: "Silver", spanish: "Plata" },
    { english: "Gold", spanish: "Oro" },
  
    // Descripciones físicas
    { english: "Tall", spanish: "Alto/a" },
    { english: "Short", spanish: "Bajo/a" },
    { english: "Thin", spanish: "Delgado/a" },
    { english: "Fat", spanish: "Gordo/a" },
    { english: "Slim", spanish: "Esbelto/a" },
    { english: "Strong", spanish: "Fuerte" },
    { english: "Weak", spanish: "Débil" },
    { english: "Handsome", spanish: "Guapo/a" },
    { english: "Beautiful", spanish: "Hermoso/a" },
    { english: "Attractive", spanish: "Atractivo/a" },
    { english: "Blonde", spanish: "Rubio/a" },
    { english: "Brunette", spanish: "Moreno/a" },
    { english: "Bald", spanish: "Calvo/a" },
    { english: "Curly", spanish: "Rizado/a" },
    { english: "Straight", spanish: "Lacio/a" },
    { english: "Eyeglasses", spanish: "Gafas" },
  
    // Habilidades
    { english: "To speak", spanish: "Hablar" },
    { english: "To listen", spanish: "Escuchar" },
    { english: "To read", spanish: "Leer" },
    { english: "To write", spanish: "Escribir" },
    { english: "To sing", spanish: "Cantar" },
    { english: "To dance", spanish: "Bailar" },
    { english: "To cook", spanish: "Cocinar" },
    { english: "To drive", spanish: "Conducir" },
    { english: "To swim", spanish: "Nadar" },
    { english: "To run", spanish: "Correr" },
    { english: "To draw", spanish: "Dibujar" },
    { english: "To paint", spanish: "Pintar" },
    { english: "To play an instrument", spanish: "Tocar un instrumento" },
    { english: "To learn", spanish: "Aprender" },
    { english: "To teach", spanish: "Enseñar" },
    { english: "To play (sports)", spanish: "Jugar (deportes)" },
  
    // Comidas
    { english: "Bread", spanish: "Pan" },
    { english: "Rice", spanish: "Arroz" },
    { english: "Pasta", spanish: "Pasta" },
    { english: "Meat", spanish: "Carne" },
    { english: "Chicken", spanish: "Pollo" },
    { english: "Fish", spanish: "Pescado" },
    { english: "Beef", spanish: "Carne de res" },
    { english: "Soup", spanish: "Sopa" },
    { english: "Salad", spanish: "Ensalada" },
    { english: "Sandwich", spanish: "Sándwich" },
    { english: "Pizza", spanish: "Pizza" },
    { english: "Hamburger", spanish: "Hamburguesa" },
    { english: "Cheese", spanish: "Queso" },
    { english: "Egg", spanish: "Huevo" },
    { english: "Bacon", spanish: "Tocino" },
    { english: "Dessert", spanish: "Postre" },
    { english: "Cake", spanish: "Pastel" },
    { english: "Ice cream", spanish: "Helado" }
  ];
  