export const vocabulario = {
  categorias: {
    frutas: [
      { english: "Apple", spanish: "Manzana", example: "I eat an apple every day." },
      { english: "Banana", spanish: "Plátano", example: "Me gusta comer plátano en el desayuno." },
      { english: "Orange", spanish: "Naranja", example: "I drink orange juice in the morning." },
      { english: "Strawberry", spanish: "Fresa", example: "Las fresas son muy dulces." },
      { english: "Grapes", spanish: "Uvas", example: "I bought grapes at the market." },
      { english: "Watermelon", spanish: "Sandía", example: "La sandía es refrescante en verano." },
      { english: "Pineapple", spanish: "Piña", example: "Pineapple is great in fruit salads." },
      { english: "Mango", spanish: "Mango", example: "El mango está de temporada." },
      { english: "Pear", spanish: "Pera", example: "A pear a day keeps the doctor away." },
      { english: "Lemon", spanish: "Limón", example: "I add lemon to my tea." },
      { english: "Peach", spanish: "Durazno", example: "El durazno está maduro." },
      { english: "Kiwi", spanish: "Kiwi", example: "Kiwi is rich in vitamin C." },
      { english: "Cherry", spanish: "Cereza", example: "I love cherries in my yogurt." },
      { english: "Avocado", spanish: "Aguacate", example: "El aguacate es perfecto para guacamole." }
    ],
    colores: [
      { english: "Red", spanish: "Rojo", example: "My car is red." },
      { english: "Blue", spanish: "Azul", example: "El cielo está muy azul hoy." },
      { english: "Green", spanish: "Verde", example: "She wore a green dress." },
      { english: "Yellow", spanish: "Amarillo", example: "Las flores son de color amarillo." },
      { english: "Black", spanish: "Negro", example: "His jacket is black." },
      { english: "White", spanish: "Blanco", example: "The cat is white." },
      { english: "Pink", spanish: "Rosa", example: "I have a pink notebook." },
      { english: "Purple", spanish: "Púrpura", example: "The flowers are purple." },
      { english: "Orange", spanish: "Naranja", example: "I like orange juice." },
      { english: "Brown", spanish: "Marrón", example: "The dog is brown." },
      { english: "Gray", spanish: "Gris", example: "The sky is gray today." },
      { english: "Beige", spanish: "Beige", example: "She has a beige sweater." },
      { english: "Silver", spanish: "Plata", example: "The ring is silver." },
      { english: "Gold", spanish: "Oro", example: "The necklace is made of gold." }
    ],
    descripciones: [
      { english: "Tall", spanish: "Alto/a", example: "He is tall and athletic." },
      { english: "Short", spanish: "Bajo", example: "She is short but very strong." },
      { english: "Thin", spanish: "Delgado", example: "He is very thin." },
      { english: "Fat", spanish: "Gordo", example: "The cat is a little fat." },
      { english: "Slim", spanish: "Esbelto", example: "She has a slim figure." },
      { english: "Strong", spanish: "Fuerte", example: "He is strong and can lift heavy weights." },
      { english: "Weak", spanish: "Débil", example: "I feel weak after the flu." },
      { english: "Handsome", spanish: "Guapo", example: "The actor is very handsome." },
      { english: "Beautiful", spanish: "Hermoso", example: "The sunset was beautiful." },
      { english: "Attractive", spanish: "Atractivo", example: "She's very attractive and charming." },
      { english: "Blonde", spanish: "Rubio", example: "She has blonde hair." },
      { english: "Brunette", spanish: "Moreno", example: "He is a tall brunette." },
      { english: "Bald", spanish: "Calvo", example: "He is bald but looks good." },
      { english: "Curly", spanish: "Rizado", example: "Her curly hair is beautiful." },
      { english: "Straight", spanish: "Lacio", example: "He has straight hair." },
      { english: "Eyeglasses", spanish: "Gafas", example: "I wear eyeglasses to read." }
    ],
    habilidades: [
      { english: "To speak", spanish: "Hablar", example: "I can speak three languages." },
      { english: "To listen", spanish: "Escuchar", example: "She listens carefully during meetings." },
      { english: "To read", spanish: "Leer", example: "I like to read books in the evening." },
      { english: "To write", spanish: "Escribir", example: "He writes in his journal every night." },
      { english: "To sing", spanish: "Cantar", example: "I love to sing in the shower." },
      { english: "To dance", spanish: "Bailar", example: "They love to dance salsa." },
      { english: "To cook", spanish: "Cocinar", example: "She knows how to cook delicious meals." },
      { english: "To drive", spanish: "Conducir", example: "I am learning to drive." },
      { english: "To swim", spanish: "Nadar", example: "We swim every weekend." },
      { english: "To run", spanish: "Correr", example: "I run every morning to stay fit." },
      { english: "To draw", spanish: "Dibujar", example: "He loves to draw cartoons." },
      { english: "To paint", spanish: "Pintar", example: "She paints landscapes in her free time." },
      { english: "To play an instrument", spanish: "Tocar un instrumento", example: "I play the guitar." },
      { english: "To learn", spanish: "Aprender", example: "I want to learn Spanish." },
      { english: "To teach", spanish: "Enseñar", example: "She teaches mathematics at the university." },
      { english: "To play (sports)", spanish: "Jugar (deportes)", example: "We play soccer every weekend." }
    ],
    comidas: [
      { english: "Bread", spanish: "Pan", example: "I need to buy bread for breakfast." },
      { english: "Rice", spanish: "Arroz", example: "Rice is a staple in many cuisines." },
      { english: "Pasta", spanish: "Pasta", example: "I love eating pasta with tomato sauce." },
      { english: "Meat", spanish: "Carne", example: "He prefers to eat meat for dinner." },
      { english: "Chicken", spanish: "Pollo", example: "We are having chicken for lunch." },
      { english: "Fish", spanish: "Pescado", example: "I like grilled fish." },
      { english: "Beef", spanish: "Carne de res", example: "Beef is a common ingredient in stews." },
      { english: "Soup", spanish: "Sopa", example: "I had chicken soup when I was sick." },
      { english: "Salad", spanish: "Ensalada", example: "She made a fresh salad for lunch." },
      { english: "Sandwich", spanish: "Sándwich", example: "I had a ham and cheese sandwich." },
      { english: "Pizza", spanish: "Pizza", example: "Let's order pizza for dinner." },
      { english: "Hamburger", spanish: "Hamburguesa", example: "He loves eating hamburgers with fries." },
      { english: "Cheese", spanish: "Queso", example: "I like cheese on my sandwich." },
      { english: "Egg", spanish: "Huevo", example: "I prefer my eggs scrambled." },
      { english: "Bacon", spanish: "Tocino", example: "Bacon and eggs are my favorite breakfast." },
      { english: "Dessert", spanish: "Postre", example: "We had chocolate cake for dessert." },
      { english: "Cake", spanish: "Pastel", example: "She baked a delicious chocolate cake." },
      { english: "Ice cream", spanish: "Helado", example: "I like vanilla ice cream." }
    ]
  }
};
